// GENERATED by app/tool/push_strings.dart from the ARB files. Do not edit.
export const pushStrings = {
  "ar": {
    "pushWaterArrivedTitle": "وصلت المياه إلى {neighborhood}",
    "pushWaterArrivedBody": "أكّد جيرانك في نفس مستوى منزلك أن المياه تصل الآن. حان وقت ملء الخزانات.",
    "pushReachedLowerTitle": "وصلت المياه إلى {neighborhood}",
    "pushReachedLowerBody": "المياه تصل الآن إلى المناطق المنخفضة من الحي، وعادةً تصل إلى المنازل المرتفعة لاحقًا.",
    "pushReminderTitle": "غدًا دور المياه في {neighborhood}",
    "pushReminderBody": "يبدأ الضخ المجدول الساعة {time}. جهّز خزاناتك."
  },
  "en": {
    "pushWaterArrivedTitle": "Water arrived in {neighborhood}",
    "pushWaterArrivedBody": "Neighbors at your level confirmed water is flowing. Time to fill your tanks.",
    "pushReachedLowerTitle": "Water reached {neighborhood}",
    "pushReachedLowerBody": "It's flowing in the lower parts of the neighborhood. Homes on higher ground usually get it later.",
    "pushReminderTitle": "Water day tomorrow in {neighborhood}",
    "pushReminderBody": "Supply is scheduled to start at {time}. Get your tanks ready."
  }
} as const;

export type PushLocale = keyof typeof pushStrings;
export type PushKey = keyof typeof pushStrings.en;
