// GENERATED by app/tool/push_strings.dart from the ARB files. Do not edit.
export const pushStrings = {
  "ar": {
    "pushWaterArrivedTitle": "وصلت المياه إلى {neighborhood}",
    "pushWaterArrivedBody": "أكّد جيرانك في نفس مستوى منزلك أن المياه تصل الآن. حان وقت ملء الخزانات.",
    "pushReachedLowerTitle": "وصلت المياه إلى {neighborhood}",
    "pushReachedLowerBody": "المياه تصل الآن إلى المناطق المنخفضة من الحي، وعادةً تصل إلى المنازل المرتفعة لاحقًا.",
    "pushReminderTitle": "غدًا دور المياه في {neighborhood}",
    "pushReminderBody": "يبدأ الضخ المجدول الساعة {time}. جهّز خزاناتك.",
    "pushScheduleStartTitle": "بدأ دور المياه في {neighborhood}",
    "pushScheduleStartBody": "الضخ مجدول من الساعة {time}. سنخبرك عندما يؤكد جيرانك وصول المياه."
  },
  "en": {
    "pushWaterArrivedTitle": "Water arrived in {neighborhood}",
    "pushWaterArrivedBody": "Neighbors at your level confirmed water is flowing. Time to fill your tanks.",
    "pushReachedLowerTitle": "Water reached {neighborhood}",
    "pushReachedLowerBody": "It's flowing in the lower parts of the neighborhood. Homes on higher ground usually get it later.",
    "pushReminderTitle": "Water day tomorrow in {neighborhood}",
    "pushReminderBody": "Supply is scheduled to start at {time}. Get your tanks ready.",
    "pushScheduleStartTitle": "Your water day in {neighborhood} starts now",
    "pushScheduleStartBody": "Supply is scheduled from {time}. We'll let you know when neighbors confirm water has arrived."
  }
} as const;

export type PushLocale = keyof typeof pushStrings;
export type PushKey = keyof typeof pushStrings.en;
