// Generates supabase/functions/_shared/push_strings.ts from the ARB files so
// push notification text lives with every other user-facing string.
//
//   dart run tool/push_strings.dart
//
// test/tool/push_strings_test.dart fails if the generated file is stale.
import 'dart:convert';
import 'dart:io';

const outputPath = '../supabase/functions/_shared/push_strings.ts';

Map<String, String> _pushMessages(String locale) {
  final arb =
      jsonDecode(File('lib/core/l10n/app_$locale.arb').readAsStringSync()) as Map<String, dynamic>;
  return {
    for (final e in arb.entries)
      if (e.key.startsWith('push')) e.key: e.value as String,
  };
}

String renderPushStrings() {
  final locales = {'ar': _pushMessages('ar'), 'en': _pushMessages('en')};
  const encoder = JsonEncoder.withIndent('  ');
  return '// GENERATED by app/tool/push_strings.dart from the ARB files. Do not edit.\n'
      'export const pushStrings = ${encoder.convert(locales)} as const;\n\n'
      'export type PushLocale = keyof typeof pushStrings;\n'
      'export type PushKey = keyof typeof pushStrings.en;\n';
}

void main() {
  File(outputPath)
    ..createSync(recursive: true)
    ..writeAsStringSync(renderPushStrings());
  stdout.writeln('Wrote $outputPath');
}
